name: hexo-Blog deploy CI

on:
  push:
    branches:
      - main

env:
  GIT_USER: yangxudong
  GIT_EMAIL: yang.xudong@outlook.com
  THEME_REPO: StuartYang/blog
  DEPLOY_REPO: StuartYang/StuartYang.github.io
  DEPLOY_BRANCH: main

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout deploy repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.DEPLOY_REPO }}
          ref: ${{ env.DEPLOY_BRANCH }}
          path: .deploy_git

      - name: 当前Node.js版本： ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: 自动化部署配置
        env:
          hexo_deploy_pri: ${{secrets.hexo_deploy_pri}}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$hexo_deploy_pri" > ~/.ssh/hexo_deploy
          chmod 600 ~/.ssh/hexo_deploy
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL

        - name: hexo所需依赖安装
        run: |
          npm install hexo-cli -g
          npm install

       - name: Hexo部署
        run: |
          hexo clean
          hexo generate
          gulp
          hexo deploy


